output:
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
  wsl:
    allow-assign-and-anything: false
  exhaustruct:
    exclude:
      - 'cobra\.Command$'
      - '.*'
  varnamelen:
    min-name-length: 1
  depguard:
    rules:
      main:
        files:
          - $all
issues:
  exclude-rules:
    - path: migrations/...
      linters:
        - gochecknoinits
        - forbidigo
        - wrapcheck
    - path: app/models/...
      linters:
        - nestif
    - path: cmd
      linters:
        - forbidigo
        - gochecknoglobals
        - gochecknoinits
    - source: "DB|CONN|ENV|migrations"
      linters:
        - gochecknoglobals
    - text: TODO
      linters:
        - godox

linters:
  disable-all: true
  enable:
    - errcheck
    - wsl
    - exhaustruct
    - gochecknoinits
    - forbidigo
    - wrapcheck
    - nestif
    - gochecknoglobals
    - godox
